import { Button, HorizontalBox, ListView, ScrollView, Slider, SpinBox, Palette, VerticalBox, CheckBox, TabWidget } from "std-widgets.slint";
import { ChatterboxConfigView, ChatterboxConfig, GenerationActions, FilePicking } from "generator.slint";
import { TopicList, TopicListItem, Audio, FilterActions } from "topics.slint";
import { Progress, ProgressDisplay, ProgressActions } from "progress.slint";
import { ExpansionsEditor } from "expansions.slint";
import { Mappings, Expansion } from "expansions.slint";
import { SubstitutionsEditor, SubstitutionsActions } from "substitutions.slint";
import { UIError, ErrorToastActions, ErrorToasts } from "errors.slint";
import { FolderExportDialogue, DBVOExportDialogue, FOMODExportDialogue, PathSelection } from "export.slint";
import { EditDialogueFilter, DialogueFilterOptions } from "filter.slint";
export  { Audio, GenerationActions, FilePicking, ProgressActions, Mappings, SubstitutionsActions, ErrorToastActions, FolderExportDialogue, DBVOExportDialogue, FOMODExportDialogue, PathSelection, FilterActions }

import { ProjectSelector } from "project_selector.slint";
export { ProjectSelector }

export global Dialogs {
    callback show_export_to_folder();
    callback show_export_to_dbvo();
    callback show_export_to_fomod();
    callback delete_short_voicelines();
}

export component AppWindow inherits Window {
    in-out property <[TopicListItem]> topicListModel;
    in-out property <ChatterboxConfig> genConfig;
    in-out property <Progress> progress;
    in-out property <[Expansion]> expansions;
    in-out property <int> allowed_expansions: 8;
    in-out property <string> substitutions_text;
    in-out property <[UIError]> errors;

    callback add_topic_from_path();
    callback remove_topic(int);
    in-out property <DialogueFilterOptions> filter_options;
    title: "VOSpeaker";
    preferred-width: 800px;
    preferred-height: 600px;
    MenuBar {
        Menu {
            title: "Project";
            Menu {
                title: "Export to...";
                MenuItem {
                    title: "Folder";
                    activated => {
                        Dialogs.show_export_to_folder();
                    }
                }
                MenuItem {
                    title: "DBVO mod";
                    activated => {
                        Dialogs.show_export_to_dbvo();
                    }
                }
                MenuItem {
                    title: "FOMOD";
                    activated => {
                        Dialogs.show_export_to_fomod();
                    }
                }
            }
        }
        Menu {
            title: "Tools";
            Menu {
                title: "Batch Actions";
                MenuItem {
                    title: "Delete Audio for Short Dialogue";
                    activated => {
                        Dialogs.delete_short_voicelines();
                    }
                }
            }
        }
    }
    VerticalLayout {
        Rectangle {
            background: Palette.background;
            vertical-stretch: 1;
            horizontal-stretch: 1;
            VerticalLayout {
                HorizontalBox {
                    vertical-stretch: 1;

                    VerticalLayout {
                        width: 30%;
                        ChatterboxConfigView {
                            config <=> genConfig;
                            height:40%;
                        }
                        TabWidget {
                            height: 60%;
                            Tab {
                                title: "Expansions";
                                ExpansionsEditor {
                                    expansions <=> expansions;
                                    allowed_expansions <=> allowed_expansions;
                                }
                            }
                            Tab {
                                title: "Substitutions";
                                SubstitutionsEditor {
                                    substitutionsText <=> substitutions_text;
                                }
                            }
                        }
                    }
                    VerticalLayout {
                        EditDialogueFilter {
                            options <=> filter_options;
                        }
                        TopicList {
                            model <=> topicListModel;
                            add_topic_from_path => {add_topic_from_path()}
                            remove_topic(idx) => {remove_topic(idx)}
                            filter_options: filter_options;
                        }
                    }
                }

                if progress.active: ProgressDisplay {
                    vertical-stretch: 0;
                    progress <=> progress;
                }

                property <bool> regen_stale;
                if !progress.active: HorizontalLayout {

                    Text {
                        text: "Mass generation";
                        horizontal-stretch: 0;
                    }
                    CheckBox {
                        text: "Regenerate stale lines";
                        checked <=> regen_stale;
                    }
                    Button {
                        horizontal-stretch: 0;
                        text: "Mass Generation";
                        clicked => {GenerationActions.mass_generate_dialogue(regen_stale)}
                    }
                }
            }
            HorizontalLayout {
                Rectangle {
                    horizontal-stretch: 1;
                }
                ErrorToasts {
                    width: 60%;
                    height: 100%;
                    errors: errors;
                }
            }
        }
    }
}
