import { Button, HorizontalBox, ListView, ScrollView, Slider, SpinBox, Palette, VerticalBox, CheckBox, TabWidget } from "std-widgets.slint";
import { ChatterboxConfigView, ChatterboxConfig, GenerationActions, FilePicking } from "generator.slint";
import { TopicList, TopicListItem, Audio } from "topics.slint";
import { Progress, ProgressDisplay, ProgressActions } from "progress.slint";
import { ExpansionsEditor } from "expansions.slint";
import { Mappings, Expansion } from "expansions.slint";
import { SubstitutionsEditor, SubstitutionsActions } from "substitutions.slint";
import { UIError, ErrorToastActions, ErrorToasts } from "errors.slint";
export  { Audio, GenerationActions, FilePicking, ProgressActions, Mappings, SubstitutionsActions, ErrorToastActions }

export component AppWindow inherits Window {
    in-out property <[TopicListItem]> topicListModel;
    in-out property <ChatterboxConfig> genConfig;
    in-out property <Progress> progress;
    in-out property <[Expansion]> expansions;
    in-out property <int> allowed_expansions: 8;
    in-out property <string> substitutions_text;
    in-out property <[UIError]> errors;
    title: "VOSpeaker";
    preferred-width: 800px;
    preferred-height: 600px;
    Rectangle {
        background: Palette.background;
        VerticalLayout {
            HorizontalBox {
                vertical-stretch: 1;

                VerticalLayout {
                    width: 30%;
                    ChatterboxConfigView {
                        config <=> genConfig;
                        height:40%;
                    }
                    TabWidget {
                        height: 60%;
                        Tab {
                            title: "Expansions";
                            ExpansionsEditor {
                                expansions <=> expansions;
                                allowed_expansions <=> allowed_expansions;
                            }
                        }
                        Tab {
                            title: "Substitutions";
                            SubstitutionsEditor {
                                substitutionsText <=> substitutions_text;
                            }
                        }
                    }
                }
                TopicList {
                    model <=> topicListModel;
                }
            }

            if progress.active: ProgressDisplay {
                vertical-stretch: 0;
                progress <=> progress;
            }

            property <bool> regen_stale;
            if !progress.active: HorizontalLayout {

                Text {
                    text: "Mass generation";
                    horizontal-stretch: 0;
                }
                CheckBox {
                    text: "Regenerate stale lines";
                    checked <=> regen_stale;
                }
                Button {
                    horizontal-stretch: 0;
                    text: "Mass Generation";
                    clicked => {GenerationActions.mass_generate_dialogue(regen_stale)}
                }
            }
        }
    }

    HorizontalLayout {
        Rectangle {
            horizontal-stretch: 1;
        }
        ErrorToasts {
            width: 60%;
            height: 100%;
            errors: errors;
        }
    }
}
