
import { ComboBox, TextEdit, SpinBox, ScrollView } from "std-widgets.slint";
export struct Expansion {
    index: int,
    name: string,
    substitutions: string
}

export global Mappings {
    pure callback expansionNames([Expansion]) -> [string];
    callback expansion_changed(string, string);
    callback max_expansions_changed(int);
}

export component ExpansionEditor inherits VerticalLayout {
    in-out property <Expansion> expansion;
    callback expansion_changed(string);

    property <bool> update-pending: false;
    update-timer := Timer {
        interval: 10ms;
        running: update-pending;
        triggered => {
            expansion_changed(te.text);
            update-pending = false;
        }
    }

    te := TextEdit {
        text: expansion.substitutions;
        placeholder-text: "Jack\nJohn\nJill";
        edited(text) => {
            update-pending = true;
            update-timer.restart();
        }
    }
}

export component ExpansionsEditor inherits VerticalLayout {
    in-out property <[Expansion]> expansions;
    in-out property <int> allowed_expansions;

    HorizontalLayout {
        Text {
            text: "Expansions per line:";
            vertical-alignment: center;
        }
        sb := SpinBox {
            minimum: 1;
            maximum: 1024;
            value <=> allowed_expansions;
            changed value => Mappings.max_expansions_changed(self.value);
        }
        padding-bottom: 15px;
    }

    cb := ComboBox {
        model: Mappings.expansionNames(expansions);
    }

    Rectangle {
        if expansions.length > 0: Rectangle {
            for expansion[i] in expansions: ExpansionEditor {
                expansion: expansion;
                expansion_changed(new_expansions) => {Mappings.expansion_changed(cb.current-value, new_expansions)}
                visible: i == cb.current-index || (cb.current-index < 0 && i == 0);
            }

            /*
            ScrollView {
                VerticalLayout {
                    for expansion[i] in expansions: VerticalLayout {
                        Text {
                            text: @tr("name: {}", expansion.name);
                        }
                        Text {
                            text: @tr("expansions: {}", expansion.substitutions);
                        }
                    }
                }
            }
            */
            /*
            VerticalLayout {
                Text {
                    text: cb.current-index;
                }
                Text {
                    text: cb.current-value;
                }
                TextEdit {
                    text: cb.current-value;
                }

                Text {
                    text: expansions[(cb.current-index >= 0 ? cb.current-index : 0)].substitutions;
                }
                TextEdit {
                    text: expansions[(cb.current-index >= 0 ? cb.current-index : 0)].substitutions;
                }
            }
            */

        }
    }
}