
import { ComboBox, TextEdit, SpinBox } from "std-widgets.slint";
export struct Expansion {
    name: string,
    substitutions: [string]
}

export global Mappings {
    pure callback expansionNames([Expansion]) -> [string];
    // TODO: remove this
    pure callback parseSubstitutions(string) -> [string];
    pure callback collapseSubstitutions([string]) -> string;
    callback expansion_changed(int, [string]);
    callback max_expansions_changed();
}

export component ExpansionEditor inherits VerticalLayout {
    in-out property <Expansion> expansion;
    callback expansion_changed([string]);

    property <bool> update-pending: false;
    update-timer := Timer {
        interval: 10ms;
        running: update-pending;
        triggered => {
            expansion_changed(Mappings.parseSubstitutions(te.text));
            update-pending = false;
        }
    }

    te := TextEdit {
        text: Mappings.collapseSubstitutions(expansion.substitutions);
        placeholder-text: "Jack\nJohn\nJill";
        edited(text) => {
            update-pending = true;
            update-timer.restart();
        }
    }
}

export component ExpansionsEditor inherits VerticalLayout {
    in-out property <[Expansion]> expansions;
    in-out property <int> allowed_expansions;

    HorizontalLayout {
        Text {
            text: "Expansions per line:";
            vertical-alignment: center;
        }
        sb := SpinBox {
            minimum: 1;
            maximum: 1024;
            value <=> allowed_expansions;
            changed value => Mappings.max_expansions_changed();
        }
        padding-bottom: 15px;
    }

    cb := ComboBox {
        model: Mappings.expansionNames(expansions);
    }

    Rectangle {
        for expansion[i] in expansions: Rectangle {
            if i == cb.current-index || (i == 0 && cb.current-index == -1): ExpansionEditor {
                expansion: expansion;
                expansion_changed(new_expansions) => {Mappings.expansion_changed(i, new_expansions)}
            }
        }
    }
}