import { LineEdit, CheckBox } from "std-widgets.slint";
export struct DialogueFilterOptions {
    search_term: string,
    search_in_spoken: bool,
    search_in_expanded: bool
}

export component EditDialogueFilter inherits HorizontalLayout {
    in-out property <DialogueFilterOptions> options;

    CheckBox {
        text: "Search in Spoken";
        changed checked => {
            options.search-in-spoken = self.checked;
        }
    }
    CheckBox {
        text: "Search in Expanded";
        changed checked => {
            options.search-in-expanded = self.checked;
        }
    }
    LineEdit {
        changed text => {
            options.search-term = self.text;
        }
    }
}